sudo: required
language: generic

services:
    - docker

# build test version of client container to run test inside of it
before_install:
    - docker build -t ericamendez/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ericamendez/react-test npm test
    # old and will throw errors - docker run ericamendez/react-test npm test -- --coverage

after_success:
    - docker build -t ericamendez/multi-client ./client
    - docker build -t ericamendez/multi-nginx ./nginx
    - docker build -t ericamendez/multi-server ./server
    - docker build -t ericamendez/multi-worker ./worker
    # take those images and push them to Docker Hub
    # first log into Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ericamendez/multi-client
    - docker push ericamendez/multi-nginx
    - docker push ericamendez/multi-server
    - docker push ericamendez/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-000784283210
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY